using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// This script manages updating the visuals of the character based on the values that are passed to it from the PlayerController.
/// NOTE: You shouldn't make changes to this script when attempting to implement the functionality for the W10 journal.
/// </summary>
public class PlayerVisuals : MonoBehaviour
{
    public Animator animator;
    public SpriteRenderer bodyRenderer;
    public PlayerController playerController;

    private int idleHash, jumpingHash, walkingHash, deathHash;

    // Start is called before the first frame update
    void Start()
    {
        bodyRenderer = GetComponent<SpriteRenderer>();
        idleHash = Animator.StringToHash("Idle");
        jumpingHash = Animator.StringToHash("Jumping");
        walkingHash = Animator.StringToHash("Walking");
        deathHash = Animator.StringToHash("Death");
    }

    // Update is called once per frame
    void Update()
    {
        VisualsUpdate();
    }

    //It is not recommended to make changes to the functionality of this code for the W10 journal.
    private void VisualsUpdate()
    {
        //animator.SetBool(isWalkingHash, playerController.IsWalking());
        //animator.SetBool(isGroundedHash, playerController.IsGrounded());

        if (playerController.currentState != playerController.previousState)
        {
            if (playerController.currentState == PlayerController.CharacterState.idle)
            {
                animator.Play(idleHash);
            }
            if (playerController.currentState == PlayerController.CharacterState.walk)
            {
                animator.Play(walkingHash);
            }
            if (playerController.currentState == PlayerController.CharacterState.jump)
            {
                animator.Play(jumpingHash);
            }
        }

        if (playerController.HasDied())
        {
            animator.Play(deathHash);
        }

        switch (playerController.GetFacingDirection())
        {
            case PlayerController.FacingDirection.left:
                bodyRenderer.flipX = true;
                break;
            case PlayerController.FacingDirection.right:
            default:
                bodyRenderer.flipX = false;
                break;
        }
    }
}
